server:
  port: 9002

spring:
  application:
    name: USER-SERVICE


# Eureka client configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost # we are running locally, if you are running on production, you need to provide production hostname